import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { formatPrice, loadContent } from "@/lib/properties";
import { ContactSection } from "@/components/contact-section";
type PageProps={params:Promise<{slug:string}>};
function getMapUrl(latitude:number,longitude:number){const offset=.012;const params=new URLSearchParams({bbox:[longitude-offset,latitude-offset,longitude+offset,latitude+offset].join(","),layer:"mapnik",marker:`${latitude},${longitude}`});return `https://www.openstreetmap.org/export/embed.html?${params}`}
export function generateStaticParams(){return loadContent().properties.map(({slug})=>({slug}))}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const {slug}=await params;const property=loadContent().properties.find(item=>item.slug===slug);return property?{title:property.name,description:property.intro}:{}}
export default async function PropertyPage({params}:PageProps){const {slug}=await params;const {site,properties}=loadContent();const property=properties.find(item=>item.slug===slug);if(!property)notFound();const facts:[[string,string|number],[string,string|number],[string,string|number],[string,string|number],[string,string|number]]=[["Suprafață utilă",`${property.areaSqm} m²`],["Teren",`${property.landSqm} m²`],["Dormitoare",property.bedrooms],["Băi",property.bathrooms],["Construită",property.yearBuilt]];const mapUrl=getMapUrl(property.mapLatitude,property.mapLongitude);return <main>
<section className="property-hero"><Image src={property.coverImage ?? property.images[0].src} alt={property.name} fill priority sizes="100vw"/><header className="nav shell overlay-nav"><a className="brand-logo" href="/properties" aria-label={site.brand}><Image src="/logo/logo-dark.png" alt="" fill sizes="112px"/></a><nav aria-label="Navigare principală"><a href="/properties">Proprietăți</a><a href="#contact">Contact</a></nav></header><div className="property-hero-copy shell"><p className="place">{property.location}<br/>{property.region}</p><h1>{property.headline}</h1><p className="price">{formatPrice(property)}</p></div></section>
{property.slug!=="casa-zorilor"&&<section className="intro-strip shell"><p className="kicker">{property.eyebrow}</p><h2>{property.intro}</h2></section>}<section className="facts shell">{facts.map(([label,value])=><div className="fact" key={label}><small>{label}</small><strong>{value}</strong></div>)}</section>
<section className="story-section shell"><h2>{property.storyTitle}</h2><div className="story-text">{property.story.map(p=><p key={p}>{p}</p>)}</div></section><section className="gallery shell">{property.images.map(image=><figure key={image.src}><div className="gallery-image"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 760px) 100vw, 50vw"/></div></figure>)}</section>
<section className="location-block shell"><div className="location-description"><p className="kicker">Împrejurimi</p><h2>{property.locationTitle}</h2><div className="location-copy"><p>{property.locationDescription}</p><div className="nearby">{property.nearby.map(item=><div key={item.name}><span>{item.name}</span><span>{item.time}</span></div>)}</div></div></div><div className="location-map"><iframe src={mapUrl} title={`Hartă — ${property.location}`} loading="lazy"/></div></section>
<ContactSection site={site} property={property.name}/><footer className="footer shell"><a className="footer-logo" href="/properties" aria-label={site.brand}><Image src="/logo/logo-dark.png" alt="" fill sizes="130px"/></a><p>{site.footerNote}</p><a href={`tel:${site.seller.phone.replace(/[^+\d]/g,"")}`}>{site.seller.phone}</a></footer></main>}
