import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { formatPrice, loadContent } from "@/lib/properties";
import { ContactSection } from "@/components/contact-section";
export default function Properties(){const {site,properties}=loadContent();const available=properties.filter(property=>property.status!=="Sold");const phoneHref=`tel:${site.seller.phone.replace(/[^+\d]/g,"")}`;return <main>
<header className="nav shell"><Link className="brand-logo" href="/properties" aria-label={site.brand}><Image src="/logo/logo-dark.png" alt="" fill sizes="112px" priority/></Link><nav aria-label="Navigare principală"><a href="#proprietati">Proprietăți</a><a href="#contact">Contact</a></nav></header>
<section className="property-index shell" id="proprietati"><div className="section-label"><span>Selecția curentă</span><span>{String(available.length).padStart(2,"0")} proprietăți</span></div>{available.map((property,index)=><Link href={`/${property.slug}`} className="property-row" key={property.slug}><div className="row-number">{String(index+1).padStart(2,"0")}</div><div className="row-image"><Image src={property.coverImage ?? property.images[0].src} alt={property.name} fill sizes="(max-width: 760px) 90vw, 42vw" priority={index===0}/><span className="status">{property.status==="For sale"?"De vânzare":property.status}</span></div><div className="row-copy"><p>{property.location}</p><h2>{property.name}</h2><div className="row-details"><span>{property.areaSqm} m²</span><span>{property.bedrooms} dormitoare</span><span>{formatPrice(property)}</span></div></div><ArrowUpRight className="row-arrow" aria-hidden="true"/></Link>)}</section>
<ContactSection site={site}/><footer className="footer shell"><Link className="footer-logo" href="/properties" aria-label={site.brand}><Image src="/logo/logo-dark.png" alt="" fill sizes="130px"/></Link><p>{site.footerNote}</p><a href={phoneHref}>{site.seller.phone}</a></footer></main>}
