import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { formatPrice, loadContent } from "@/lib/properties";
import { ContactSection } from "@/components/contact-section";
export default function Properties(){const {site,properties}=loadContent();const available=properties.filter(property=>property.status!=="Sold");return <main>
<header className="nav shell"><span className="wordmark">{site.brand}<span>.</span></span><nav aria-label="Navigare principală"><a href="#proprietati">Proprietăți</a><a href="#contact">Contact</a></nav></header>
<section className="home-hero shell"><p className="kicker">Proprietăți alese cu grijă · Transilvania</p><h1>Locuri în care<br/><em>viața se așază frumos.</em></h1><div className="hero-bottom"><p>O selecție mică de case reprezentate în exclusivitate, pentru oameni care caută mai mult decât metri pătrați.</p><a href="#proprietati" className="circle-link" aria-label="Vezi proprietățile"><ArrowDown size={20}/></a></div></section>
<section className="property-index shell" id="proprietati"><div className="section-label"><span>Selecția curentă</span><span>{String(available.length).padStart(2,"0")} proprietăți</span></div>{properties.map((property,index)=><Link href={`/${property.slug}`} className="property-row" key={property.slug}><div className="row-number">{String(index+1).padStart(2,"0")}</div><div className="row-image"><Image src={property.coverImage ?? property.images[0].src} alt={property.name} fill sizes="(max-width: 760px) 90vw, 42vw" priority={index===0}/><span className={`status ${property.status==="Sold"?"sold":""}`}>{property.status==="For sale"?"De vânzare":property.status}</span></div><div className="row-copy"><p>{property.location}</p><h2>{property.name}</h2><div className="row-details"><span>{property.areaSqm} m²</span><span>{property.bedrooms} dormitoare</span><span>{formatPrice(property)}</span></div></div><ArrowUpRight className="row-arrow" aria-hidden="true"/></Link>)}</section>
<section className="about shell"><p className="kicker">Despre noi</p><div><h2>Mai puține proprietăți.<br/><em>Mai multă atenție.</em></h2><p>Lucrăm personal, discret și exclusiv. Cunoaștem fiecare casă pe care o reprezentăm și spunem povestea ei cu sinceritate — fără zgomot, fără grabă.</p><a className="text-link" href={`mailto:${site.email}`}>Să vorbim <ArrowUpRight size={16}/></a></div></section>
<ContactSection site={site}/><footer className="footer shell"><span className="wordmark">{site.brand}<span>.</span></span><p>{site.footerNote}</p><a href={`mailto:${site.email}`}>{site.email}</a></footer></main>}
